baseURL = "https://mikezhangziyi.github.io/blog/"   
languageCode = "zh-cn"   # 或 "en-us"
title = "Mike's Blog"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
paginate = 5

[params]
  env = "production"
  title = "Mike's Blog"
  description = "Recording life, technology and essays"
  author = "Mike"
  DateFormat = "2006-01-02"
  defaultTheme = "auto"   # 自动深浅模式
  hideSummary = false      # 关键！隐藏摘要/预览，只显示标题
  ShowReadingTime = false 
  ShowWordCount = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true         # 隐藏目录

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true