baseURL = "https://mikeogilvy.github.io/blog/"
languageCode = "zh-cn"
title = "Mike's Blog"
theme = "PaperMod"

enableRobotsTXT = true
paginate = 5

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
  customCSS = ["css/extended.css"]
  env = "production"
  description = "Recording life, technology and essays"
  author = "Mike"
  defaultTheme = "auto"
  comments = true

  ShowToc = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true

[label]
  icon = "https://raw.githubusercontent.com/MikeZhangZiyi/blog/refs/heads/main/static/images/logo.jpg"
  iconHeight = 35

[params.profileMode]
  enabled = true
  title = "Mike Ogilvy "
  subtitle = "<span class='description'></span>"
  imageUrl = "https://raw.githubusercontent.com/MikeZhangZiyi/blog/refs/heads/main/static/images/logo.jpg"
  imageWidth = 120
  imageHeight = 120

[[params.socialIcons]]
name = "github"
url = "https://github.com/MikeZhangZiyi"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/MikeOgilvy94"

[[params.socialIcons]]
name = "Telegram"
url = "https://t.me/MikeOgilvy"

[params.assets]
    favicon = "https://raw.githubusercontent.com/MikeZhangZiyi/blog/refs/heads/main/static/images/logo.jpg"

[params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 2
    # 关键：设置权重。Title 权重最高，Content 权重低一些
    keys = ["title", "permalink", "summary", "content"]


[[menu.main]]
    identifier = "posts"
    name = "📝 Posts"
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "tags"
    name = "🏷️ Tags"
    url = "/tags/"
    weight = 20

[[menu.main]]
    identifier = "search"
    name = "🔍 Search"
    url = "/search/"
    weight = 30

[markup]
  [markup.goldmark.renderer]
    unsafe = true