baseURL = "https://mikeogilvy.github.io/blog/"
languageCode = "zh-cn"
title = "Mike's Blog"
theme = "PaperMod"

enableRobotsTXT = true
paginate = 5

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
  customCSS = ["css/extended.css"]
  env = "production"
  description = "Recording life, technology and essays"
  author = "Mike"
  defaultTheme = "auto"
  comments = true

  ShowToc = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true

[label]
  icon = "https://mikeogilvy.github.io/blog/Avatar.jpg"
  iconHeight = 35

[params.profileMode]
  enabled = true
  title = "Mike Ogilvy "
  subtitle = "<span class='description'></span>"
  imageUrl = "https://mikeogilvy.github.io/blog/Avatar.jpg"
  imageWidth = 120
  imageHeight = 120

[[params.socialIcons]]
name = "github"
url = "https://github.com/MikeOgilvy"

[[params.socialIcons]]
name = "X"
url = "https://x.com/MikeOgilvy94"

[[params.socialIcons]]
name = "Telegram"
url = "https://t.me/MikeOgilvy"

[[params.socialIcons]]
name = "Email"
url = "mailto:mikeogilvy25@gmail.com"


[params.assets]
    favicon = "/ico/favicon.ico"

[params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 2
    keys = ["title", "permalink", "summary", "content"]


[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40

[[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 50

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[[menu.main]]
    identifier = "archives"
    name = "Archive" 
    url = "/archives/"
    weight = 25

[[menu.main]]
    identifier = "Friends"
    name = "Friends"
    url = "/friends"
    weight = 30

[[menu.main]]
    name = "Photography"
    url = "/photography/"
    weight = 23

[markup]
  [markup.goldmark.renderer]
    unsafe = true